apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootcampjs-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootcampjs-js
  template:
    metadata:
      labels:
        app: bootcampjs-js
    spec:
      containers:
        - name: bootcampjs-js
          image: inseefrlab/bootcampjs-js:0.1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_PATH
              value: 'https://example-api.fr'
